### PR TITLE
Case 3

### PR DESCRIPTION
**Pull request by TahHoang**
return output = -1 if input is negative 
change the queue order

### CODE REVIEW

**Comment by TahHoang** [comment]
may approve case 2 ngay cho t  (Quote Phuong: thang ra test case bi ngao da)
tong % thue d phai 1.35 ma la 1.27

**Comment by TahHoang** [comment]
fix bug case 4

**Comment by johnnybinh** [comment]
Good work!
keep on good work

**Comment by johnnybinh** [comment]
@TahHoang  fix case 3, endless loop

**Comment by TahHoang** [comment]
@johnnybinh no loop, pls retry

**Comment by johnnybinh** [comment]
still loop @TahHoang , please fix

**Comment by johnnybinh** [comment]
fix , lgtm

**Pull request merged**
